language: node_js

node_js:
 - "8.9.4"

cache:
  directories:
  - node_modules 

before_install:
 - npm install -g firebase-tools
 - npm install

script:
 - "Echo deploying"

after_success:
 - npm run build
 - firebase deploy --non-interactive --token $FIREBASE_TOKEN

branches:
  only:
    - master
